#+TITLE: Levain
#+Time-stamp: <2024-08-01 16:27:06 lperrin>
#+DESCRIPTION: Python/SAGE classes, LaTeX macros files, file/project templates, and all the small stuff I regularly need to use or copy/paste into my work as researcher 


The purpose of this repository is to store (both for me and for
others) all the various small scripts, macros files, project
templates, and whatever else that I often need to comeback to on a
regular basis during my day-to-day work.

* Python Utils
The =py= folder contains several python classes that help me when
running some experiments in Python (or, most often SAGE):
- =prg= is a small SHA-256 based deterministic PRNG. It provides
  hopefully high-quality random outputs, and its seed must be set by
  hand which helps with reproducibility.
- =LogBook= is an easy to use class that helps me generate
  experimental results that are in a usable form: as a human readable
  report (in the terminal and/or in a file), and as an importable
  SAGE/Python module file that will simplify post-processing of the
  result.



